-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgADAeuFvqnNHgViVI
UDKwn8veoXR+YEd8w3UkKjHBAaCgCgYIKoZIzj0DAQehRANCAASfMBGPlMATEUWa
qtsaWYiuXrODj/IQI9aG67J+Pnb2B5dGmQh9kz/v24y+HdlJKMuzY7D8fftyNW2r
oZKFFM/d
-----END PRIVATE KEY-----