export enum ResponseMessage {
  SUCCESS = 'Success',
  INTERNAL_SERVER_ERROR = 'Internal server error',
  INVALID_CREDENTIAL = 'Invalid credentials',
  UPDATED_SUCCESSFULLY = 'Updated successfully',
  EMAIL_SENDING_ERROR = 'Failed to send email',
  INVALID_INPUT = 'Invalid input',
  GENERIC_ERROR = 'Generic Error',
  INVALID_COUNTRY = 'Invalid country',
  INVALID_DATE = 'Invalid date',
  INVALID_TIME = 'Invalid time',
  INVALID_ZIP_CODE = 'Invalid zip code',
  EMAIL_CONFIRMED = 'Email Confirmed Successfully',
  FORGOT_PASSWORD_EMAIL = 'Please Check Your Email To Reset Password',
  USER_ALREADY_EXISTS = 'User with the same email already exists',
  TOKEN_EXPIRED = 'Token expired',
  INVALID_TOKEN = 'Invalid token',
  INVALID_USERNAME_OR_PASSWORD = 'Invalid email or password',
  INACTIVE_ACCOUNT = 'Account is not active.',
  IMAGES_ALLOW = 'Image allow',
  EMAIL_DUPLICATE = 'Email already exists',
  USERNAME_DUPLICATE = 'Username already exists',
  USER_NOT_FOUND = 'User not found',
  RESET_CODE_EXPIRED = 'Reset code has expired',
  MEDIA_NOT_EXIST = 'Media not exist',
  INVALID_IMAGE_FORMAT = 'Invalid file format, allowed images: (jpg,png,jpeg)',
  INVALID_FILE_FORMAT = 'Invalid file format, allowed only: (pdf,jpg,png,jpeg,csv)',
  RESET_CODE_INVALID = 'Invalid reset code',
  RESET_PASSWORD_SUCCESS = 'Password reset successfully',
  UNAUTHORIZED = 'Unauthorized',
  CANNOT_SEND_SELF_REQUEST = 'You cannot send a friend request to yourself',
  REQUEST_ALREADY_EXISTS = 'Friendship request already exists',
  FRIEND_REQUEST_SENT_SUCCESSFULLY = 'Friend request sent successfully',
  FRIENDSHIP_NOT_FOUND = 'Friendship not found',
  FRIENDSHIP_ALREADY_EXISTS = 'Friendship already exists',
  FRIENDSHIP_UPDATED = 'Friendship updated successfully',
  FRIENDSHIP_REMOVED = 'Friendship Removed',
  FRIEND_REQUEST_CANCELLED = 'Friend request cancelled successfully',
  BLOCKED_USER = 'User is blocked or has blocked you',
  WALLET_TRANSACTION_NOT_FOUND = 'Wallet transaction not found',
  INVALID_TRANSACTION_TYPE = 'Invalid transaction type',
  INSUFFICIENT_BALANCE = 'Insufficient balance',
  WALLET_ADDRESS_MISMATCH = 'Wallet address does not match',
  CALL_NOT_FOUND = 'Call not found',
  CALL_TOKEN_GENERATION_FAILED = 'Failed to generate call token',
  INVALID_CALL_TYPE = 'Invalid call type',
  CALL_ALREADY_EXISTS = 'Call already exists',
  CALL_SEARCH_NOT_FOUND = 'Call search not found',
  CHAT_SESSION_NOT_FOUND = 'Chat session not found',
  CHATBOT_PROCESSING_ERROR = 'Failed to process chat request',
  OPENAI_SERVICE_ERROR = 'OpenAI service error',
  CHAT_ROOM_NOT_FOUND = 'Chat room not found',
  CHAT_MESSAGE_NOT_FOUND = 'Chat message not found',
  UNAUTHORIZED_CHAT_ROOM_ACCESS = 'You do not have access to this chat room',
  CHAT_ROOM_CREATION_FAILED = 'Failed to create chat room',
  MESSAGE_SENDING_FAILED = 'Failed to send message',
  CHAT_ROOM_ALREADY_EXISTS = 'Chat room already exists',
  INVALID_CHAT_ROOM_TYPE = 'Invalid chat room type',
  MORALIS_STREAM_NOT_FOUND = 'Moralis stream not found',
  MORALIS_API_ERROR = 'Moralis API error',
  WALLET_TRANSACTION_FAILED = 'Wallet transaction failed',
  REFERRAL_NOT_FOUND = 'Referral not found.',
  REFERRAL_ALREADY_CLAIMED = 'Referral reward already claimed.',
  REFERRAL_LIMIT_NOT_REACHED = 'Referral goal not yet reached.',
  DUPLICATE_REFERRAL = 'Referral with this email already exists.',
  MESSAGE_REPORT_NOT_FOUND = 'Message report not found',
  CANNOT_SELF_REPORT = 'You cannot report your own messages',
  DUPLICATE_REPORT = 'You have already reported this message',
  UNAUTHORIZED_REPORT_ACTION = 'You are not authorized to perform this action on reports',
  INVALID_PASSWORD = 'Invalid Password',
  PASSWORD_NOT_MATCH = 'Password not match',
  SAME_PASSWORD = 'Old and new password cannot be same',
  INVALID_EMAIL = 'Invalid email',
  ADMIN_CREATION_ERROR = 'ADMIN_CREATION_ERROR',
  ADMIN_EMAIL_NOT_REGISTERED = 'ADMIN_EMAIL_NOT_REGISTERED',
  ADMIN_ALREADY_EXISTS = 'ADMIN_ALREADY_EXISTS',
  TWOFA_ALREADY_ENABLED = 'TWOFA_ALREADY_ENABLED',
  TWOFA_DISABLED = 'TWOFA_DISABLED',
  INVALID_2FA = 'INVALID_2FA',
  INVALID_ADMIN = 'INVALID_ADMIN',
  INACTIVE_ADMIN = 'INACTIVE_ADMIN',
  TWOFA_NOT_CONFIGURED = 'TWOFA_NOT_CONFIGURED',
  USER_SERVICE_ERROR = 'Error processing user request',
}

export enum ResponseCode {
  SUCCESS = 200,
  CREATED_SUCCESSFULLY = 201,
  INTERNAL_ERROR = 500,
  NOT_FOUND = 404,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  INVALID_INPUT = 617,
  GENERIC_ERROR = 600,
  MEDIA_NOT_EXIST = 614,
  INVALID_CREDENTIAL = 618,
  EMAIL_DUPLICATE = 619,
  USERNAME_DUPLICATE = 620,
  INACTIVE_ACCOUNT = 621,
  INVALID_USERNAME_OR_PASSWORD = 622,
  USER_NOT_FOUND = 623,
  RESET_CODE_EXPIRED = 624,
  RESET_CODE_INVALID = 625,
  RESET_PASSWORD_SUCCESS = 626,
  CANNOT_SEND_SELF_REQUEST = 627,
  REQUEST_ALREADY_EXISTS = 628,
  FRIENDSHIP_NOT_FOUND = 629,
  FRIENDSHIP_ALREADY_EXISTS = 630,
  BLOCKED_USER = 631,
  WALLET_TRANSACTION_NOT_FOUND = 632,
  INVALID_TRANSACTION_TYPE = 633,
  INSUFFICIENT_BALANCE = 634,
  WALLET_ADDRESS_MISMATCH = 635,
  CALL_NOT_FOUND = 636,
  CALL_TOKEN_GENERATION_FAILED = 637,
  INVALID_CALL_TYPE = 638,
  CALL_ALREADY_EXISTS = 639,
  CALL_SEARCH_NOT_FOUND = 640,
  CHAT_SESSION_NOT_FOUND = 641,
  CHATBOT_PROCESSING_ERROR = 642,
  OPENAI_SERVICE_ERROR = 643,
  CHAT_ROOM_NOT_FOUND = 644,
  CHAT_MESSAGE_NOT_FOUND = 645,
  UNAUTHORIZED_CHAT_ROOM_ACCESS = 646,
  CHAT_ROOM_CREATION_FAILED = 647,
  MESSAGE_SENDING_FAILED = 648,
  CHAT_ROOM_ALREADY_EXISTS = 649,
  INVALID_CHAT_ROOM_TYPE = 650,
  MORALIS_STREAM_NOT_FOUND = 651,
  MORALIS_API_ERROR = 652,
  WALLET_TRANSACTION_FAILED = 653,
  REFERRAL_NOT_FOUND = 654,
  REFERRAL_ALREADY_CLAIMED = 655,
  REFERRAL_LIMIT_NOT_REACHED = 656,
  DUPLICATE_REFERRAL = 657,
  MESSAGE_REPORT_NOT_FOUND = 658,
  CANNOT_SELF_REPORT = 659,
  DUPLICATE_REPORT = 660,
  UNAUTHORIZED_REPORT_ACTION = 661,
  ADMIN_ALREADY_EXISTS = 662,
  TOKEN_EXPIRED = 663,
  EMAIL_NOT_REGISTERED = 664,
  INVALID_2FA = 665,
  TWOFA_DISABLED = 666,
  INVALID_ADMIN = 667,
  TWOFA_NOT_CONFIGURED = 668,
  TWOFA_ALREADY_ENABLED = 669,
  INVALID_TOKEN = 670,
  ADMIN_EMAIL_NOT_REGISTERED = 671,
  INACTIVE_ADMIN = 672,
  USER_SERVICE_ERROR = 673,
}

export enum NodeEnv {
  TEST = 'test',
  DEVELOPMENT = 'development',
  PRODUCTION = 'production',
}

export enum CallType {
  VOICE = 'voice',
  VIDEO = 'video',
}

export enum ChatRoomType {
  INDIVIDUAL = 'individual',
  GROUP = 'group',
}

export enum MessageStatus {
  SENT = 'sent',
  DELIVERED = 'delivered',
  READ = 'read',
}

export enum TransactionType {
  PAYMENT = 'Payment',
  REWARD = 'Reward',
  STAKING = 'Staking',
}

export enum TransactionStatus {
  PENDING = 'Pending',
  COMPLETED = 'Completed',
  FAILED = 'Failed',
}

export enum ReferralPlatform {
  TELEGRAM = 'Telegram',
  WHATSAPP = 'WhatsApp',
  LINE = 'Line',
  ZALO = 'Zalo',
  KAKAOTALK = 'KakaoTalk',
  FBMESSENGER = 'FBMessenger',
  OTHER = 'Other',
}

export enum AccountStatus {
  ACTIVE = 'Active',
  DISABLE = 'Disabled',
}

export enum UserRoles {
  SUPER_ADMIN = 'superAdmin',
  ADMIN = 'admin',
  USER = 'user',
}
